### PR TITLE
Added OWASP Benchmark Java

### PR DESCRIPTION
**Pull request by rewtd**

### CODE REVIEW

**Review by psiinon — CHANGES_REQUESTED** [review]
And again

**Comment by rewtd** [comment]
Sorted, thanks!

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Looks good but now has a merge conflict

**Comment by rewtd** [comment]
Fixed the merge issue - which I caused with a previous PR.

**Comment by rewtd** [comment]
Looks like I can't merge even though the PR's approved - you'll have to merge it @psiinon

**Comment by psiinon** [comment]
Thanks @rewtd !

**Pull request merged**
